name: CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}

env:
  PNPM_VERSION: 6.19.0

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm run test
